### ISSUE TITLE
Memory Leak Unity 2019.3.12f1

### ISSUE THREAD

**Issue by meckzqz** [JayPeet/UnityImGUI#3] opened 2020-05-08 23:42 UTC
I spent a half hour trying out this package in Unity 2019.3.12f1. Entering play mode in the included demo scene unfortunately resulted in an immediate memory leak, quickly filling up gigabytes of ram. I was unable to determine where the leak may have occurred myself. Investigating a snapshot taken in Unity's memory profiler tells me that the memory did not exist in Unity's managed memory, and the consumed memory persisted after exiting play mode.

**Comment by JayPeet** [comment] 2020-05-11 12:35
Heya, not seen that happen before in any of my projects.

Any chance of you zipping up an example project of it happening so I can fix it? :)

**Comment by meckzqz** [comment] 2020-05-13 20:49
Hello, thanks for the response! Here's a project that I just created with the default 3D template. I imported the release version of your package, installed the Unity Collections package from package manager, and the memory leak occurs in your test scene on my machine. It may be worth mentioning that the rate of memory usage grows with how many ImGUI windows I open with the demo window.

[UnityImGui.zip](https://github.com/JayPeet/UnityImGUI/files/4624596/UnityImGui.zip)

**Comment by JayPeet** [comment] 2020-05-15 20:54
Woah. You are 100% correct.

I'm investigating where that's happening now, and will get back to you shortly (Hopefully)

**Comment by d11jxpeet** [comment] 2020-05-19 11:11
I know what the issue is, but finding the time to go fix it is hard. Hoping to have a soloution in, within 2 or 3 days, along with some other improvements

**Comment by JayPeet** [comment] 2020-05-19 11:12
I know what the issue is, but finding the time to go fix it is hard. Hoping to have a soloution in, within 2 or 3 days, along with some other improvements.

**Comment by JayPeet** [comment] 2020-05-22 12:42
Hey again, should be fixed in https://github.com/JayPeet/UnityImGUI/releases/tag/v0.2

Let me know if you come across anything else :)

**Closed as completed** 2020-10-06 17:25 UTC
