### ISSUE TITLE
"Microsoft (R) Visual C# Compiller version 2.9.1.65535 (9d34608e)" after installing UnityImGui package

### ISSUE THREAD

**Issue by 0xWeebz** [JayPeet/UnityImGUI#4] opened 2021-01-11 22:13 UTC
Hey I'm a little confused on how to actually implement this seeing as there is no documentation. any help is appreciated.

**Comment by JayPeet** [comment] 2021-01-11 22:22
Howdy!

After bringing the unity package into your project from the releases, add the ImGuiPluginHook prefab to your scene.

Now, you can write the usual ImGui code (Thanks to ImGUI.NET) in the Update function of one of your scripts.

eg.
```
using UnityEngine;
using ImGuiNET;
public class MyAwesomeGameScript : MonoBehaviour
{
    public System.Numerics.Vector3 selectedColor;
    public void Update()
    {
        ImGui.Begin("Interesting Game Window");

        if (ImGui.Button("TestButton"))
            Debug.Log("Button Pressed!");

        ImGui.ColorEdit3("Colour Picker", ref selectedColor); 
        ImGui.End();
    }
}
```

And when running you will get this
![image](https://user-images.githubusercontent.com/5172736/104245005-6c42b400-545b-11eb-8c14-2fa2f6cf6373.png)

**Comment by 0xWeebz** [comment] 2021-01-11 22:22
Holy fast reply thank you!

**Comment by 0xWeebz** [comment] 2021-01-11 22:23
![image](https://user-images.githubusercontent.com/74121133/104245148-9757e400-5418-11eb-9fc9-81e01bc974cd.png)

**Comment by JayPeet** [comment] 2021-01-11 22:24
Whats in your project console? Any compile errors?

**Comment by 0xWeebz** [comment] 2021-01-11 22:26
Uh yeah I'm trying to google that too and its a little difficult 
![image](https://user-images.githubusercontent.com/74121133/104245344-eef64f80-5418-11eb-9af2-e0934afb8333.png)
I'm not really too advanced in game development just heard from a friend that unity uses C# and I should try it out

**Comment by JayPeet** [comment] 2021-01-11 22:27
Thats a strange issue. Which version of unity are you on?

**Comment by JayPeet** [comment] 2021-01-11 22:28
And is this on windows?

**Comment by 0xWeebz** [comment] 2021-01-11 22:28
latest 2019.4.17f1
![image](https://user-images.githubusercontent.com/74121133/104245495-3977cc00-5419-11eb-8c31-b95cbbd0034d.png)

**Comment by 0xWeebz** [comment] 2021-01-11 22:28
And correct I am on windows.

**Comment by JayPeet** [comment] 2021-01-11 22:30
Hmm, very strange! Thats the exact version that I took that screen shot from a moment ago

It might be something with your visual studio install. I would run the visual studio installer
![image](https://user-images.githubusercontent.com/5172736/104245586-6dc0ac00-545c-11eb-9808-c7ed92a707d8.png)

Then modify your install
![image](https://user-images.githubusercontent.com/5172736/104245602-744f2380-545c-11eb-914f-40c95b32b8dc.png)

And then check to make sure you have all the c sharp things installed that you would need (I am not sure which things you would actually need)
![image](https://user-images.githubusercontent.com/5172736/104245660-921c8880-545c-11eb-9af6-bc9f2868a722.png)

**Comment by JayPeet** [comment] 2021-01-11 22:31
Also, in the project settings in your unity project.
In the player tab
![image](https://user-images.githubusercontent.com/5172736/104245725-b1b3b100-545c-11eb-897a-bffaca0f6466.png)
Is your Api compatibility level set to this?

**Comment by 0xWeebz** [comment] 2021-01-11 22:32
Uh I closed unity assuming that it would need to restart after messing with visual studio packages I will relaunch it one second.

**Comment by JayPeet** [comment] 2021-01-11 22:32
Sure no rush, Ill be around for a couple hours or so 😄

**Comment by 0xWeebz** [comment] 2021-01-11 22:33
Unities OnGUI is a lot easier to get running but it doesn't fit my game style, of more modern.

**Comment by JayPeet** [comment] 2021-01-11 22:34
OnGUI also ends up allocating each frame if I recall, and is generally bad for performance unless you really mess with some of the internal DLL code relating to it.

ImGUI is really nice, I use it for quick debug menus quite a lot. I wish I had more time to make this perfect to use in all situations, but I just dont have the time :(

**Comment by 0xWeebz** [comment] 2021-01-11 22:35
Please Excuse my grammar english isn't my first language.

**Comment by 0xWeebz** [comment] 2021-01-11 22:37
I'm creating an online platformer game and I need it for an administration/moderation menu

**Comment by JayPeet** [comment] 2021-01-11 22:38
> 
> 
> Please Excuse my grammar english isn't my first language.

Don't worry, I understand you fine :)

Sounds like it could be a good game, I wish you luck!

**Comment by 0xWeebz** [comment] 2021-01-11 22:58
![image](https://user-images.githubusercontent.com/74121133/104247900-6f1eb400-541d-11eb-8b8b-8432cf304fde.png)

**Comment by 0xWeebz** [comment] 2021-01-11 22:58
I dont see the api compatability

**Comment by JayPeet** [comment] 2021-01-11 22:59
It would be in the other settings drop down

**Comment by 0xWeebz** [comment] 2021-01-11 22:59
![Uploading image.png…]()

**Comment by 0xWeebz** [comment] 2021-01-11 23:00
![image](https://user-images.githubusercontent.com/74121133/104248094-b73dd680-541d-11eb-9254-2ad51cf11fe1.png)

**Comment by 0xWeebz** [comment] 2021-01-11 23:08
I'm so confused

**Comment by JayPeet** [comment] 2021-01-11 23:11
Hmm, I have no idea why you might be getting this issue then. I have never seen it before.

It is probably something with your setup. Does it do the same issue in a new project, when you don't have UnityImGUI added?

**Comment by 0xWeebz** [comment] 2021-01-11 23:21
No.

**Comment by 0xWeebz** [comment] 2021-01-11 23:24
do i need to install ImGUI.net via nuget?

**Comment by JayPeet** [comment] 2021-01-11 23:26
No, it should have came with it. Did you check online for that error? It seems like a specific issue

**Comment by 0xWeebz** [comment] 2021-01-11 23:33
i tried and no results

**Comment by 0xWeebz** [comment] 2021-01-11 23:34
Ima attempt to fix this on my own please leave this issue open i will post any solutions I can come up with for anyone else who has this problem

**Comment by JayPeet** [comment] 2021-01-11 23:43
Sure can do, Im going to go to bed shortly. I'll keep an eye out to see if I can figure it out too :)

**Comment by JayPeet** [comment] 2021-01-28 13:22
I had no luck trying to reproduce this, did you ever figure anything else out about it @0xWeebz?

**Comment by JayPeet** [comment] 2024-05-09 12:29
Closing as no further info.

Coming back to this project soon since I have plans to have a stab at rebuilding this project with what I have learnt over the past couple years.

**Closed as completed by JayPeet** 2024-05-09 12:29 UTC
Labels: bug
